version: "3.7"

services:
  frontend-routinesapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: frontend-routinesapp
    tty: true
    ports:
      - "4200:80"
    environment:
      API_URL: http://localhost:5555
